name: Lint

on:
  workflow_dispatch:
  push:
    branches:
      - '**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - uses: actions/cache@v4
        with:
          path: |
            ~/.yarn
            node_modules
          key: v1-deps-${{ hashFiles('yarn.lock') }}

      - run: yarn

      - run: yarn nx graph --file=./projects.json

      - name: Remix Libs Linting
        run: node ./apps/remix-ide/ci/lint-targets.js